[WIP] implementation compatible with libyang2
CESNET/libyang-python pull request #20
Opened 2021-03-16 12:11 UTC by Dajvid

Hi, as I promised some time ago, I'm opening a pull request with my current progress on the python wrapper for libyang2. It still needs a lot of love, but I would like to get some feedback.

As I was writing it while libyang2 was still under heavy development without stable API, and I wasn't even able to keep up with the latest changes lately (this version is compatible with libyang2 on commit 45802b59e0ef479a1af8cf373bb24b50d348bbbd), I will have to do a lot of refactoring.

Overall I'm quite happy with context and schema modules, on the other hand, I'm not happy with the data module, I found it very hard to create friendly API for some complicated lyd_* functions. I tried some approaches with generalization and merging of those functions, but without much success, so I'm planning to try to implement the equivalent of your "data dictionary" for that.

I'm also planning to:
- Reuse your setup for CI/CD and installation.
- Work on backwards compatibility (methods vs properties, add methods to ensure compatibility when needed and possible...).
- Try to reuse most of your e2e tests.
- Write proper documentation.

2021-03-16 13:24 UTC, rjarry commented
Hi @Dajvid 

I'll take some time to make a proper review this week.

Thanks

2021-03-17 09:53 UTC, rjarry commented
Hi David,

Before digging deeper into the code I have a few general remarks:

- Please preserve the existing MIT license.
- Do not remove my copyrights, add a line with your name.
- Do not change code unless it is necessary (`README.rst`, `cffi/build.py`, etc.).

Also, I wonder if it could be possible to continue to support both versions of libyang.

2021-03-17 09:55 UTC, rjarry requested changes
Hi David,

Before digging deeper into the code I have a few general remarks:

- Please preserve the existing MIT license.
- Do not remove my copyrights, add a line with your name.
- Do not change code unless it is necessary (`README.rst`, `cffi/build.py`, etc.).
- Since you are removing the `libyang` package. No need to use a different `libyang2`.

Also, I wonder if it could be possible to continue to support both versions of libyang.

2021-06-14 11:45 UTC, wisotzky commented
@rjarry, I don't think there is any value to support both version. Since libyang2 was released a month ago, the original libyang was obsoleted. As long the python API stays compatible, can move to version 2 straight ahead.

@Dajvid, it would be great to get some timelines... There are some important enhancements in libyang2, which I would plan to use. Not sure, if I can support here...

2021-06-25 09:33 UTC, Dajvid commented
I'm sorry, didn't have time for this lately, but I can get back to work now and during the summer.

I would definitely appreciate some help, mainly with the improvements of data module, overall api improvements, installation scripts and CI setup.

Support both versions at once would be very complicated and I don't think it's a good idea.
Full compatibility across both versions is not possible in my opinion, but both versions can be similar and require just small changes. Similarly as libyang2 is not fully backwards compatible...

@rjarry I will adress your remarks until monday and then we can continue.
@wisotzky It should be already somewhat usable (obvisously with a lot of complications, but main parts are covered), I need to do a lot of refactoring because this was designed and implemented mostly during last year before libyang2 was released and didn't have stable api yet at that time. And as for the timeline, I would definitely like to get this done and release ready until the end of this summer (or end of September to be precise), because after that my free time will be very limited again.

2021-06-28 08:42 UTC, rjarry requested changes
Hi @Dajvid 

I did not read everything. This is almost impossible to review. Too many changes. Too many of them are completely unrelated to libyang2.

Git history is very important (to me at least :)) and I wait to avoid changing code unless we have a good reason to do so. And more importantly, never mix topics in the same commits.

I think the best course of action would be to discuss the overall design choices that you have made and see how that can be integrated into the current code base without a complete rewrite.

Would that be ok for you?

2021-06-28 08:42 UTC, rjarry commented on .gitignore
> +cython_debug/
I am not sure this is relevant to libyang2. Please only add the required changes. We do not need to exclude all this.

2021-06-28 08:42 UTC, rjarry commented on MANIFEST.in
> -include README.rst
Why remove this file?

2021-06-28 08:42 UTC, rjarry commented on Makefile
> -# Copyright (c) 2018-2020 Robin Jarry
Please preserve my copyritghts

2021-06-28 08:42 UTC, rjarry commented on Makefile
> +	python -m coverage html
I do not think you need to change anything in this file.

2021-06-28 08:42 UTC, rjarry commented on README.rst
> -Thank you in advance for your contributions!
Why delete this file?

2021-06-28 08:42 UTC, rjarry commented on cffi/build.py
> +                          py_limited_api=False,
Please do not change lines unless required. Do not mix reformatting/refactoring with libyang2 related stuff. Also, I doubt this matches black coding style :)

2021-10-16 17:33 UTC, closed without merging