context: parse with high level function
CESNET/libyang-python pull request #31
Opened 2022-04-19 09:13 UTC by jeanseb6wind

Context parsing should use high level function instead of low level.

2022-04-19 09:33 UTC, rjarry requested changes
You did not explain why you made this change. Could you motivate a bit?

Thanks

2022-04-19 09:33 UTC, rjarry commented on libyang/context.py
> -                ffi.NULL,
If I'm not mistaken, `parent` is now ignored.

2022-04-19 09:33 UTC, rjarry commented on tests/test_data.py
> -
Why did you remove this test?

2022-04-19 14:51 UTC, jeanseb6wind commented
It's ok now.
We have to use the libyang wrapper around `parse_data` insead of using `parse_data` directly

2022-04-19 15:35 UTC, rjarry commented
You only explained *what* your commit does. Not *why* you made it. I don't understand why this is needed.

2022-05-05 07:03 UTC, jeanseb6wind commented
Hello @rjarry, is it ok for you now that I have updated the commit message ?

2022-05-10 20:04 UTC, rjarry requested changes
I finally understand the idea behind this patch :) Please see my comments.

2022-05-10 20:04 UTC, rjarry commented on libyang/context.py
> +            in_data=fileobj,
This should call `lyd_parse_data_filepath` directly. I don't see the point in wrapping the call into a generic parse_data that ends up calling specific functions.

2022-05-10 20:04 UTC, rjarry commented on pylintrc
> +	unnecessary-lambda,
I think this is not necessary anymore.

2022-05-10 20:04 UTC, rjarry commented on libyang/context.py
> +        )
This should call `lyd_parse_data_fd` directly. I don't see the point in wrapping the call into a generic parse_data that ends up calling specific functions.

2022-05-10 20:05 UTC, rjarry commented on libyang/context.py
> +            dnode,
This is really ugly. Please avoid this kind of code at all costs :)

2022-05-11 09:33 UTC, jeanseb6wind commented
abandonned, useless

2022-05-11 09:33 UTC, closed without merging